export const INGRESA_USUARIO     = "INGRESA_USUARIO",
             ESTABLECE_CONSULTA   = "ESTABLECE_CONSULTA",
             ESTABLECE_RECETA     = "ESTABLECE_RECETA",
             ESTABLECE_RECETARIO  = "ESTABLECE_RECETARIO",
             AGREGA_A_HISTORIAL   = "AGREGA_A_HISTORIAL";