export const // USUARIO -LOGIN/SIGNUP
             BUSCAR_USUARIO_PENDIENTE = "BUSCAR_USUARIO_PENDIENTE",
             BUSCAR_USUARIO_EXITO     = "BUSCAR_USUARIO_EXITO",
             BUSCAR_USUARIO_ERROR     = "BUSCAR_USUARIO_ERROR",
             // USUARIO - LOGOUT
             RETIRAR_USUARIO_PENDIENTE = "RETIRAR_USUARIO_PENDIENTE",
             RETIRAR_USUARIO_EXITO     = "RETIRAR_USUARIO_EXITO",
             RETIRAR_USUARIO_ERROR     = "RETIRAR_USUARIO_ERROR",
             // RECETARIO
             BUSCAR_RECETARIO_PENDIENTE = "BUSCAR_RECETARIO_PENDIENTE",
             BUSCAR_RECETARIO_EXITO     = "BUSCAR_RECETARIO_EXITO",
             BUSCAR_RECETARIO_ERROR     = "BUSCAR_RECETARIO_ERROR",
             // RECETA
             BUSCAR_RECETA_PENDIENTE = "BUSCAR_RECETA_PENDIENTE",
             BUSCAR_RECETA_EXITO     = "BUSCAR_RECETA_EXITO",
             BUSCAR_RECETA_ERROR     = "BUSCAR_RECETA_ERROR",          

             GUARDAR_CONSULTA  = "GUARDAR_CONSULTA",
             ABRIR_RECETA      = "ABRIR_RECETA",
             AGREGAR_HISTORIAL = "AGREGAR_HISTORIAL",
             AGREGAR_FAVORITO  = "AGREGAR_FAVORITO",
             REMOVER_FAVORITO  = "REMOVER_FAVORITO";