export const // USUARIO
             REGISTRAR_USUARIO_PENDIENTE = "REGISTRAR_USUARIO_PENDIENTE",
             REGISTRAR_USUARIO_EXITO     = "REGISTRAR_USUARIO_EXITO",
             REGISTRAR_USUARIO_ERROR     = "REGISTRAR_USUARIO_ERROR",
             BUSCAR_USUARIO_PENDIENTE = "BUSCAR_USUARIO_PENDIENTE",
             BUSCAR_USUARIO_EXITO     = "BUSCAR_USUARIO_EXITO",
             BUSCAR_USUARIO_ERROR     = "BUSCAR_USUARIO_ERROR",
             // RECETARIO
             BUSCAR_RECETARIO_PENDIENTE = "BUSCAR_RECETARIO_PENDIENTE",
             BUSCAR_RECETARIO_EXITO     = "BUSCAR_RECETARIO_EXITO",
             BUSCAR_RECETARIO_ERROR     = "BUSCAR_RECETARIO_ERROR",

             GUARDAR_CONSULTA  = "GUARDAR_CONSULTA",
             ABRIR_RECETA      = "ABRIR_RECETA",
             AGREGAR_HISTORIAL = "AGREGAR_HISTORIAL",
             AGREGAR_FAVORITO = "AGREGAR_FAVORITO";